import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import Header from "./components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Desk Saarthi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="dashboar-layout" className="w-full h-screen flex bg-secondary" >
          <Sidebar/>  
          <div className="main-content flex flex-col flex-grow ">
            <Header />
            <main className="content overflow-y-scroll ">
              {children}
              </main>
          </div>

        </div>
      </body>
    </html>
  );
}
