# .github/workflows/deploy-server.yml
name: CI/CD server

on:
  push:
    branches: [main]
    paths:
      - 'server/**'       # trigger only when server code changes
      - '.github/**'       # or when workflow itself changes

defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['24.x']  
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}


      - name: Cache npm
        uses: actions/cache@v4

        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('server/**/package-lock.json') }}

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: dist/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: server-dist
          path: server/dist
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_PATH }}
            rm -rf dist && mkdir -p dist
            rsync -avz --delete server/dist/ .
            npm install --omit=dev
            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
