# .github/workflows/deploy-server.yml
name: CI/CD server

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: server/package-lock.json # <-- specify path here

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Build TypeScript
        run: npm run build
        working-directory: ./server

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/"
          target: "/home/ubuntu/Desk-Sarthi/"
          rm: true

      - name: Install dependencies and restart server on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/Desk-Sarthi/server
            cd /home/ubuntu/Desk-Sarthi/server
            # Create .env file with secrets
            cat > .env << EOF
            API_OPEN_WEATHER=${{ secrets.API_OPEN_WEATHER }}
            SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
            SPOTIFY_REDIRECT_URI=${{ secrets.SPOTIFY_REDIRECT_URI }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            PORT=${{ secrets.PORT }}
            HIVEMQ_HOST=${{ secrets.HIVEMQ_HOST }}
            HIVEMQ_USERNAME=${{ secrets.HIVEMQ_USERNAME }}
            HIVEMQ_PASSWORD=${{ secrets.HIVEMQ_PASSWORD }}
            CLIENT_URL=${{ secrets.CLIENT_URL }}
            EOF
            npm install --production
            pm2 restart all
