# .github/workflows/deploy-server.yml
name: CI/CD server

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: server/package-lock.json # <-- specify path here

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Build TypeScript
        run: npm run build
        working-directory: ./server

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/"
          target: "/home/ubuntu/Desk-Sarthi/"
          rm: true
          excludes: ".env"

      - name: Install dependencies and restart server on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Desk-Sarthi/server
            npm install --production
            pm2 restart all
